[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
#bevy = { version = "0.12.0", features = ["serialize","dynamic_linking","file_watcher"] }
bevy = "0.12.1"

[profile.dev]
# opt-level = 1

[profile.dev.package."*"]
#opt-level = 3
