[build]
#jobs = 2
#rustc-wrapper = 'C:\programs\cargo\bin\sccache.exe'

[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
#linker = "rust-lld.exe"
#rustflags = ["-Zshare-generics=n"]

[profile.dev]
#debug = 1

[profile.release]
#incremental = true
#opt-level = 0

